"""Top-level package for seaborn_extensions."""

from .swarmboxenplot import swarmboxenplot
from .annotated_clustermap import (
    activate as activate_annotated_clustermap,
    clustermap,
)
from .volcano import volcano_plot

try:
    # Even though there is no "imc/_version" file,
    # it should be generated by
    # setuptools_scm when building the package
    from imc._version import version

    __version__ = version
except ImportError:
    from setuptools_scm import get_version as _get_version

    version = __version__ = _get_version(root="..", relative_to=__file__)

__author__ = """Andre Rendeiro"""
__email__ = "afrendeiro@gmail.com"
